### ISSUE TITLE
Chaos splitting test fails occasionally

### ISSUE THREAD

**Issue by masaimu** [sofastack/sofa-jraft#230]
### Describe the bug

``com.alipay.sofa.jraft.rhea.chaos.ChaosRocksDBLeaderReadTest#chaosSplittingTest`` fails occasionally caused by "Invalid region version error (region split or merge happened)."

```text
java.util.concurrent.ExecutionException: com.alipay.sofa.jraft.rhea.errors.InvalidRegionVersionException: Invalid region version error (region split or merge happened).

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at com.alipay.sofa.jraft.rhea.client.FutureHelper.get(FutureHelper.java:46)
	at com.alipay.sofa.jraft.rhea.client.DefaultRheaKVStore.bGet(DefaultRheaKVStore.java:370)
	at com.alipay.sofa.jraft.rhea.chaos.AbstractChaosTest.chaosSplittingCheckData(AbstractChaosTest.java:220)
	at com.alipay.sofa.jraft.rhea.chaos.AbstractChaosTest.chaosSplittingTest(AbstractChaosTest.java:210)
Caused by: com.alipay.sofa.jraft.rhea.errors.InvalidRegionVersionException: Invalid region version error (region split or merge happened).
```
The reason I guess as below:
1. In ``chaosSplittingTest`` we call ``com.alipay.sofa.jraft.rhea.client.RheaKVCliService#rangeSplit`` to prepare the scenario.
2. Then ``RangeSplitRequest`` has been sent to RheaKV server, and the split task has also been published to the ring buffer in ``com.alipay.sofa.jraft.core.NodeImpl#apply``, but it has not been applied by ``com.alipay.sofa.jraft.rhea.storage.KVStoreStateMachine#batchApply``;
3. So the RegionEpoch version of leader has not been increased yet. At the moment, ``RheaKVStore#bGet`` is called by client in ``com.alipay.sofa.jraft.rhea.chaos.AbstractChaosTest#chaosSplittingCheckData``, and the client will get overdue RegionEpoch version in ``com.alipay.sofa.jraft.rhea.client.DefaultRheaKVStore#internalGet``.
4. So the failure occurs.

### Expected behavior

``chaosSplittingTest`` passed.

### Actual behavior

``chaosSplittingTest`` failed.

### Steps to reproduce

Running the test repeatedly util it fails.

### Environment
Local IDE.

- SOFAJRaft version:  1.2.5
- JVM version (e.g. `java -version`):  "1.8.0_171"
- OS version (e.g. `uname -a`): MacOS 10.14.5
- Maven version:
- IDE version:

**Comment by fengjiachun** [comment]
I think this is not a bug, I will explain it later.

**Comment by fengjiachun** [comment]
1. First, splitting operation is the same as a normal request through the raft process.

2. When the raft log is successfully replicated to the majority, the leader node will perform the splitting operation first. After the splitting succeeds, the local routing table information (`RegionRouteTable`) will be refreshed first, then the success status will be returned to the client.

3. In the chaos test, call the request of read request may be a follower node, but at this time the follower node is still executing split, so it will carry the old `regionEpoch` to request the leader, and the leader will return the request failure, which is correct behavior.

4. The follower node must wait until its splitting completed to get the latest routing table information. This is because there is no real placement driver (we use `FakePlacementDriverClient` in chaos test).
Therefore, the follower cannot refresh the routing table information during the retry process, and can only wait until the split is completed.

This is why the test fails occasionally. Before the follower successfully refreshes the routing table information, we always make the request fails. We have no better way to make the follower to get the new routing table more quickly.

**Comment by masaimu** [comment]
ok, i see. 
thx, i close issue.
