### ISSUE TITLE
About the counter example,do you process redirect when the leader is transferd

### ISSUE THREAD

**Issue by kexianjun** [sofastack/sofa-jraft#267]
About the counter example,do you process redirect when the leader is transferd?

**Comment by masaimu** [comment]
The `ValueResponse` from counter server includes a field named "redirect" which means the real leader peer if it is not null. The client can request to the real leader again if your business thinks it's necessary. 
In this simple example, the client just provides a notification to user, details as below:
![image](https://user-images.githubusercontent.com/12896475/64754008-ead1cd80-d557-11e9-86d2-c8c6f653d1c2.png)
The first and third request fails because they are sent to follower, so the response redirect field shows the real leader.

**Comment by kexianjun** [comment]
ok, got it. So sofa-jraft just left the client to process redirect.
